/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LinkScrollCom: typeof import('./components/linkScrollCom.vue')['default']
    ListPage: typeof import('./components/listPage.vue')['default']
    Navigatorbar: typeof import('./components/navigatorbar.vue')['default']
    PageWrapper: typeof import('./components/pageWrapper.vue')['default']
    PullList: typeof import('./components/pullList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabbar: typeof import('./components/tabbar.vue')['default']
  }
}
